version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_HOST: 'localhost'

  app:
    build: .
    container_name: 'app'
    command: sh -c "python Consumer.py & uvicorn Producer:app --reload --port=8000 --host=0.0.0.0"
    depends_on:
      - rabbitmq
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
